// template-react-ts/src/login/index.tsx
import { useNavigate } from "react-router-dom";
import { useLoginInfoStore } from "../core/store";
import { Button, Checkbox, Form, Input, message } from "antd";
import { LockOutlined, UserOutlined } from "@ant-design/icons";
import { flexCenterOpts } from "../core/style/utils";
import { defaultLinkPath, defaultLoginInfo, defaultUserInfo } from "./config";

interface ILogin {
  username: string;
  password: string;
  remember?: boolean;
}

export default function Login() {
  const { updateLoginInfo } = useLoginInfoStore((state) => state);
  const [form] = Form.useForm();
  const navigate = useNavigate();

  const onFinish = (values: ILogin) => {
    if (values.username === defaultUserInfo.username && values.password === defaultUserInfo.password) {
      updateLoginInfo(defaultLoginInfo);
      navigate(defaultLinkPath);
    } else {
      message.warning("用户名或密码错误，请检查！");
    }
  };

  return (
    <div
      css={[
        {
          height: globalThis.document.documentElement.clientHeight,
          backgroundImage: "url(https://gw.alipayobjects.com/zos/rmsportal/TVYTbAXWheQpRcWDaDMu.svg)",
          backgroundSize: "100% 100%",
          backgroundRepeat: "no-repeat",
        },
        flexCenterOpts(),
      ]}
    >
      <Form
        name="login"
        form={form}
        style={{ width: 356 }}
        initialValues={{ username: defaultUserInfo.username, password: defaultUserInfo.password, remember: true }}
        onFinish={onFinish}
      >
        <Form.Item name="username" rules={[{ required: true, message: "Please input your Username!" }]}>
          <Input prefix={<UserOutlined className="site-form-item-icon" />} placeholder={defaultUserInfo.username} />
        </Form.Item>
        <Form.Item name="password" rules={[{ required: true, message: "Please input your Password!" }]}>
          <Input
            prefix={<LockOutlined className="site-form-item-icon" />}
            type="password"
            placeholder={defaultUserInfo.password}
          />
        </Form.Item>
        <Form.Item>
          <Form.Item name="remember" valuePropName="checked" noStyle>
            <Checkbox>Remember me</Checkbox>
          </Form.Item>
          <a css={{ float: "right" }} href="">
            Forgot password
          </a>
        </Form.Item>
        <Form.Item>
          <Button type="primary" htmlType="submit" className="login-form-button" style={{ width: "100%" }}>
            Log in
          </Button>
          Or <a href="">register now!</a>
        </Form.Item>
      </Form>
    </div>
  );
}

// template-vue-ts/src/login/index.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { defaultUserInfo, useUserInfoStore } from "../core/store/user";
import { ElMessage } from "element-plus";
import router from "../core/router";

const userStore = useUserInfoStore();
const defaultAccountInfo = {
  username: "zhangshan",
  password: "123456",
};

const formData = ref({
  ...defaultAccountInfo,
});
const height = computed(() => {
  return globalThis.document.documentElement.clientHeight + "px";
}).value;
onMounted(() => {
  localStorage.clear();
});

const onSubmit = () => {
  const { username, password } = formData.value;
  if (username === defaultAccountInfo.username && password === defaultAccountInfo.password) {
    ElMessage({
      message: "登录成功",
      type: "success",
    });
    userStore.updateUserInfo(defaultUserInfo);
    router.push({ name: "Dashboard" });
  } else {
    console.log("error");
    ElMessage({
      message: "用户名或者密码不对，请检查！",
      type: "warning",
    });
  }
};
</script>

<template>
  <div class="wrap">
    <el-form label-position="top" label-width="100px" :model="formData" style="width: 420px">
      <el-form-item label="用户名">
        <el-input v-model="formData.username" aria-placeholder="请输入用户名" />
      </el-form-item>
      <el-form-item label="密码">
        <el-input v-model="formData.password" aria-placeholder="请输入密码" />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSubmit">登录</el-button>
      </el-form-item>
    </el-form>
  </div>
</template>

<style scoped>
.wrap {
  height: v-bind("height");
  display: flex;
  justify-content: center;
  align-items: center;
  background-image: url(https://gw.alipayobjects.com/zos/rmsportal/TVYTbAXWheQpRcWDaDMu.svg);
  background-size: 100% 100%;
  background-repeat: no-repeat;
}
</style>
